sudo: true

# install Heroku CLI 
# (based on https://github.com/travis-ci/apt-package-whitelist/issues/375)
addons:
  apt:
    sources:
      - heroku
    packages:
      - heroku-toolbelt
env: 
  global: 
  - secure: $DEPLOY_KEY     
language: java
jdk:
- oraclejdk8
after_success:
- "./gradlew build jacocoTestReport coveralls"
- "./gradlew sonarqube -Dsonar.login=$SONAR_TOKEN -Dsonar.branch.name=$TRAVIS_BRANCH
  -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=$SONAR_ORG"
