sudo: true
env: 
"-DOMAIN_NAME": product-ms-java
"-EUREKA_URL": https://$EUREKA_USER:$EUREKA_PASSWORD@soft-8025-eureka.herokuapp.com
language: java
jdk:
- oraclejdk8
after_success:
- "./gradlew build jacocoTestReport coveralls"
- "./gradlew sonarqube -Dsonar.login=$SONAR_TOKEN -Dsonar.branch.name=$TRAVIS_BRANCH
  -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=$SONAR_ORG"
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: david.ahern26@gmail.com
  password:
    secure: DLXh9vukIRIGxwcrz8A00rECSqa2M1wM7sgbqsiQlNx8hBUuw0sxZcu8PDogdHfqwnOoQAO5HSLo0nkaRPEYcmfk+ks8RmduwzyACCePMGFCW4MeJ/glsgmrVeeYKNH+2ssmmjbSMlEsVWRCuOvDtag4ZIVMuGEAwpAqDrMd/ipSyzgeZ8jBsEU87ejbr3H5GMn0i/rqEEnDVOBWE1Sd2zjf5yYcva5dNC5tdk5/J7mNv+xtZbDQPmalrDOW97WYxvVK/ihyMIHu1kGLSmOcYLSDj0qvlECR4gXa2BCDN9FwRR2/bZmH1bnQWxCx7ha5LKwr/ulMEFjMRjKkquMONGGUpRNnadXnsstr5J/QtS1xskOY56yfOoBaorGTZapUxWygPFM58CxjKUb99W88SsOHqVt2+QO7J0ozP/fVQoH+DSgPBra4B66SA3vUkkAx9SOT5HR9wJUG5ViQzjbHbExB2SbtxDGKHk/Ds70yjg3iRQXclYvh0kIPfEUSefnx2B8JfI8jyJb0hDsoWmwTDhcW6QhkEDPDWhH5bYpRXcReqlJOvRkzfmbWJPgBu831u30mrqXycsmxKM6BADjWd1Hnpcdyu5ay+FhY4UJdE7uOxhbYtIjnlFeujSK2GH+jqOk3qJRbhqSZXgu5ktk3hPX08+/QKAXh2JGuUyrjBIQ=
  organization: thor
  space: soft8025
  on:
    repo: SOFT8025-msc/product-ms-java
    branch: master
